### ISSUE TITLE
[BUG] `<!---[CodeSnippet](file=...)-->` not working for me

### ISSUE THREAD

**Issue by lestephane** [quantummaid/documaid#18]
**Describe the bug**
Adding `<!---[CodeSnippet](file=step1/pom.xml)-->` to `quantummaid-tutorials/aws-lambda/README.md` causes the following error:

```text
[INFO] --- documaid:0.9.25:validate (default-cli) @ parent ---
[INFO] DocuMaid started
[ERROR] DocuMaid finished with 1 errors.
[ERROR] Found [CodeSnippet] tag with incorrect code for '<!---[CodeSnippet](file=step1/pom.xml)-->' (in path <SCRUBBED>/quantummaid-tutorials/aws-lambda/README.md)
```

The `step1/pom.xml`file does exist.

Is `file=...` really supported in `CodeSnippet`, as mentioned on [this usage page](https://github.com/quantummaid/documaid/blob/master/documentation/Usage.md)?

**Comment by lestephane** [comment]
hmm it looks like the :validate goal always fails, until i run the :generate goal for the first time.
It's confusing.

**Comment by quantummaiddeveloper** [comment]
Yes, the validate goal will only ensure that the build fails when the documentation is out of sync. This is important for CI/CD systems. Needs more documentation though.
